apiVersion: v1
kind: ConfigMap
metadata:
  name: lead-manager-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  ConnectionStrings__LeadManagerDatabase: "Host=postgres;Port=5432;Database=lead_manager;Username=postgres;Password=postgres"
  ConnectionStrings__Redis: "redis:6379"
  ConnectionStrings__Mongo: "mongodb://mongo:27017"
  Jwt__Issuer: "lead-manager-api"
  Jwt__Audience: "lead-manager-clients"
  Jwt__ExpiresInMinutes: "60"
  LeadScoring__Enabled: "false"
  Integrations__HubSpot__Enabled: "false"
  Integrations__Salesforce__Enabled: "false"
  Integrations__WhatsAppMeta__Enabled: "false"
  Integrations__WhatsAppTwilio__Enabled: "false"
