apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lead-manager
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - postgres.yaml
  - redis.yaml
  - mongo.yaml
  - api.yaml
  - worker.yaml
  - frontend.yaml
  - ingress.yaml
  - hpa-api.yaml
