apiVersion: v1
kind: Secret
metadata:
  name: lead-manager-secrets
type: Opaque
stringData:
  Jwt__SigningKey: "replace-with-strong-key-with-32-plus-characters"
  Auth__Users__0__Username: "admin"
  Auth__Users__0__Password: "admin123!"
  Auth__Users__0__Role: "admin"
  Auth__Users__1__Username: "marketing"
  Auth__Users__1__Password: "marketing123!"
  Auth__Users__1__Role: "marketing"
  Auth__Users__2__Username: "vendas"
  Auth__Users__2__Password: "vendas123!"
  Auth__Users__2__Role: "vendas"
  Integrations__HubSpot__ApiKey: ""
  Integrations__Salesforce__ApiKey: ""
  Integrations__WhatsAppMeta__ApiKey: ""
  Integrations__WhatsAppTwilio__ApiKey: ""
